#these are the general for an led(inplace of led buzzer also ok i guess)

import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(18,GPIO.OUT)

#in place of string u will get in the string spoken by person
string=input()
lis=[]
#time i expressed in units not in real time
for i in string:
    lis.append(i)
    lis.append(' ')
    if (i=='A' or i=='a'):
        GPIO.output(18,GPIO.HIGH)
        time.sleep(1)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(3)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
    elif (i=='B' or i=='b'):
        GPIO.output(18,GPIO.HIGH)
        time.sleep(1.5)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(0.5)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(0.5)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(0.5)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
    elif (i=='c' or i=='C'):
        GPIO.output(18,GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(18,GPIO.LOW)
        time.sleep(0.1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(0.1)
        GPIO.output(18,GPIO.LOW)
        time.sleep(0.1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(0.3)
        GPIO.output(18,GPIO.LOW)
        time.sleep(0.1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(0.1)
        GPIO.output(18,GPIO.LOW)
    elif (i=='D' or i=='d'):
        GPIO.output(18,GPIO.HIGH)
        time.sleep(3)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(1)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(1)
        GPIO.output(18,GPIO.LOW)
    elif(i=='E' or i=='e'):
        GPIO.output(18,GPIO.HIGH)
        time.sleep(1)
        GPIO.output(18,GPIO.LOW)
    elif(i==' '):
        GPIO.output(18,GPIO.LOW)
        time.sleep(3)
    elif(i=='F' or i=='f'):
        GPIO.output(18,GPIO.HIGH)
        time.sleep(1)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(1)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(3)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(1)
        GPIO.output(18,GPIO.LOW)
    elif(i=='G' or 'g'):
        GPIO.output(18,GPIO.HIGH)
        time.sleep(3)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(3)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(1)
        GPIO.output(18,GPIO.LOW)
    elif(i=='H' or 'h'):
        GPIO.output(18,GPIO.HIGH)
        time.sleep(1)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(1)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(1)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(1)
        GPIO.output(18,GPIO.LOW)
    elif(i=='I' or 'i'):
        GPIO.output(18,GPIO.HIGH)
        time.sleep(1)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(1)
        GPIO.output(18,GPIO.LOW)
    elif(i=='j' or 'J'):
        GPIO.output(18,GPIO.HIGH)
        time.sleep(1)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(3)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(3)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(3)
        GPIO.output(18,GPIO.LOW)
    elif(i=='K' or 'k'):
        GPIO.output(18,GPIO.HIGH)
        time.sleep(3)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(1)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(3)
        GPIO.output(18,GPIO.LOW)
    elif(i=='L' or 'l'):
        GPIO.output(18,GPIO.HIGH)
        time.sleep(1)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(3)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(3)
        GPIO.output(18,GPIO.LOW)
        time.sleep(1)
        GPIO.output(18,GPIO.HIGH)
        time.sleep(3)
        GPIO.output(18,GPIO.LOW)
        
        
    
   
        
        



        
